/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gephi.desktop.legend.manager;

import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultListCellRenderer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.gephi.attribute.api.AttributeModel;
import org.gephi.desktop.preview.api.PreviewUIController;
import org.gephi.graph.api.Graph;
import org.gephi.legend.api.LegendController;
import org.gephi.legend.api.LegendModel;
import org.gephi.legend.spi.CustomLegendItemBuilder;
import org.gephi.legend.spi.LegendItem;
import org.gephi.legend.spi.LegendItemBuilder;
import org.gephi.legend.spi.LegendItemRenderer;
import org.gephi.preview.api.*;
import org.gephi.preview.spi.PreviewUI;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.lookup.ServiceProvider;

/**
 *
 * @author edubecks
 */
@ServiceProvider(service = PreviewUI.class, position = 404)
public class LegendManagerUI extends javax.swing.JPanel implements PreviewUI, PropertyChangeListener {

    private final LegendController legendController;
    private final PreviewUIController previewUIController;
    

    /**
     * Creates new form LegendManagerUI
     */
    public LegendManagerUI() {
        legendController = LegendController.getInstance();
        legendController.addListener(this);
        previewUIController = Lookup.getDefault().lookup(PreviewUIController.class);
        initComponents();
        tooltipRenderer = new ComboboxToolTipRenderer();
        builderTypeComboBox.setRenderer(tooltipRenderer);

        registerLegendBuilders();

        numberOfItemsLabel.setVisible(false);
        numberOfItemsTextField.setVisible(false);
    }

    @Override
    public void propertyChange(PropertyChangeEvent event) {
        if (event.getSource() instanceof LegendController) {
            Item selectedItem = (Item) event.getNewValue();
            if (selectedItem != null && selectedItem != activeLegendsComboBox.getSelectedItem()) {
                selectActiveItemInCombobox(selectedItem);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        addLegendButton = new javax.swing.JButton();
        legendItemBuildersComboBox = new javax.swing.JComboBox();
        builderTypeComboBox = new javax.swing.JComboBox();
        legendManagerPanel = new javax.swing.JPanel();
        activeLegendsComboBox = new javax.swing.JComboBox();
        activeLegendLabel = new javax.swing.JLabel();
        renderersComboBox = new javax.swing.JComboBox();
        legendPropertiesPanel = new javax.swing.JPanel();
        removeLegendButton = new javax.swing.JButton();
        numberOfItemsTextField = new javax.swing.JTextField();
        numberOfItemsLabel = new javax.swing.JLabel();
        rendererLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        addLegendButton.setText(org.openide.util.NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.addLegendButton.text")); // NOI18N
        addLegendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLegendButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(addLegendButton, gridBagConstraints);

        legendItemBuildersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legendItemBuildersComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(legendItemBuildersComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(builderTypeComboBox, gridBagConstraints);

        legendManagerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.legendManagerPanel.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP)); // NOI18N
        legendManagerPanel.setLayout(new java.awt.GridBagLayout());

        activeLegendsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeLegendsComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        legendManagerPanel.add(activeLegendsComboBox, gridBagConstraints);

        activeLegendLabel.setText(org.openide.util.NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.activeLegendLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        legendManagerPanel.add(activeLegendLabel, gridBagConstraints);

        renderersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderersComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        legendManagerPanel.add(renderersComboBox, gridBagConstraints);

        legendPropertiesPanel.setMinimumSize(new java.awt.Dimension(152, 57));
        legendPropertiesPanel.setPreferredSize(new java.awt.Dimension(152, 57));
        legendPropertiesPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        legendManagerPanel.add(legendPropertiesPanel, gridBagConstraints);

        removeLegendButton.setText(org.openide.util.NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.removeLegendButton.text")); // NOI18N
        removeLegendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLegendButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        legendManagerPanel.add(removeLegendButton, gridBagConstraints);

        numberOfItemsTextField.setColumns(2);
        numberOfItemsTextField.setText(org.openide.util.NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.numberOfItemsTextField.text")); // NOI18N
        numberOfItemsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfItemsTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        legendManagerPanel.add(numberOfItemsTextField, gridBagConstraints);

        numberOfItemsLabel.setText(org.openide.util.NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.numberOfItemsLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        legendManagerPanel.add(numberOfItemsLabel, gridBagConstraints);

        rendererLabel.setText(org.openide.util.NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.rendererLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        legendManagerPanel.add(rendererLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(legendManagerPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void refreshActiveLegendsComboBox() {
        LegendModel legendModel = legendController.getLegendModel();
        Item activeLegendItem = legendModel.getActiveLegendItem();
        activeLegendsComboBox.removeAllItems();
        if (activeLegendItem != null) {
            ArrayList<Item> legendItems = legendModel.getLegendItems();
            for (Item item : legendItems) {
                activeLegendsComboBox.addItem(item);
            }

            activeLegendsComboBox.setSelectedItem(activeLegendItem);
        } else {
            activeLegendsComboBox.setSelectedIndex(-1);
        }
        refreshRenderers(activeLegendItem);
        refreshPropertySheet();
    }

    private void addLegendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLegendButtonActionPerformed
        Graph graph = null;
        AttributeModel attributeModel = null;

        LegendModel legendModel = legendController.getLegendModel();
        Integer newItemIndex = legendModel.getCurrentIndex();

        LegendItemBuilder builder = (LegendItemBuilder) legendItemBuildersComboBox.getSelectedItem();

        CustomLegendItemBuilder customBuilder = ((CustomLegendItemBuilderWrapper) builderTypeComboBox.getSelectedItem()).builder;
        if (customBuilder.isAvailableToBuild()) {

            Item item = builder.createCustomItem(newItemIndex, graph, attributeModel, customBuilder);

            // adding item to legend manager
            legendController.addItemToLegendModel(item);
            refreshActiveLegendsComboBox();
        } else {
            JOptionPane.showMessageDialog(
                    null, customBuilder.stepsNeededToBuild(),
                    NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.stepsNeededToBuildItem"),
                    JOptionPane.INFORMATION_MESSAGE,
                    null);
        }
        
        previewUIController.refreshPreview();
    }//GEN-LAST:event_addLegendButtonActionPerformed

    private void refreshPropertySheet() {
        PreviewController previewController = Lookup.getDefault().lookup(PreviewController.class);
        PreviewModel previewModel = previewController.getModel();

        // check if previewModel exists
        if (previewModel == null) {
            return;
        }

        legendPropertiesPanel.removeAll();
        
        Item activeLegendItem = (Item) activeLegendsComboBox.getSelectedItem();

        if (activeLegendItem != null) {
            PropertySheet propertySheet = new PropertySheet();

            propertySheet.setNodes(new Node[]{new LegendNode(propertySheet, activeLegendItem, previewModel.getProperties())});
            propertySheet.setDescriptionAreaVisible(true);
            legendPropertiesPanel.add(propertySheet, BorderLayout.CENTER);
        }
        legendPropertiesPanel.repaint();
    }

    private void removeLegendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLegendButtonActionPerformed
        // check wheter an element is active or not
        if (activeLegendsComboBox.getSelectedIndex() == -1) {
            return;
        }

        LegendModel legendModel = legendController.getLegendModel();

        Integer activeLegend = ((Item) activeLegendsComboBox.getSelectedItem()).getData(LegendItem.ITEM_INDEX);
        legendModel.removeItem(activeLegend);
        refreshActiveLegendsComboBox();
        
        previewUIController.refreshPreview();
    }//GEN-LAST:event_removeLegendButtonActionPerformed

    private void activeLegendsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeLegendsComboBoxActionPerformed
        System.out.println("@Var: activeLegendsComboBox.getSelectedItem(): "+activeLegendsComboBox.getSelectedItem());
        if(activeLegendsComboBox.getSelectedItem()!=null){
            Item activeLegendItem = (Item) activeLegendsComboBox.getSelectedItem();
            Object currentRenderer = activeLegendItem.getData(LegendItem.RENDERER);
            System.out.println("@Var: OLD currentRenderer: "+currentRenderer);
            
            setActiveItem(activeLegendItem);
            refreshRenderers(activeLegendItem);
            renderersComboBox.setSelectedItem(currentRenderer);
            currentRenderer = activeLegendItem.getData(LegendItem.RENDERER);
            System.out.println("@Var: NEW currentRenderer: "+currentRenderer);
        }
    }//GEN-LAST:event_activeLegendsComboBoxActionPerformed

    public void selectActiveItemInCombobox(Item activeLegendItem) {
//        setActiveItem(activeLegendItem);
//        refreshRenderers(activeLegendItem);
        activeLegendsComboBox.setSelectedItem(activeLegendItem);
        
    }

    public void setActiveItem(Item activeLegendItem) {
        if (activeLegendItem != null
                && activeLegendsComboBox.getSelectedItem() != null) {

//            Item currentActiveLegendItem = (Item) activeLegendsComboBox.getSelectedItem();
//            if (currentActiveLegendItem.equals(activeLegendItem)) {
//                return;
//            }

//            Object currentRenderer = activeLegendItem.getData(LegendItem.RENDERER);
//            renderersComboBox.setSelectedItem(currentRenderer);


            Boolean hasDynamicProperties = activeLegendItem.getData(LegendItem.HAS_DYNAMIC_PROPERTIES);
            numberOfItemsLabel.setVisible(hasDynamicProperties);
            numberOfItemsTextField.setVisible(hasDynamicProperties);

            if (hasDynamicProperties) {
                numberOfItemsTextField.setText(activeLegendItem.getData(LegendItem.NUMBER_OF_DYNAMIC_PROPERTIES).toString());
            }

            legendController.selectItem(activeLegendItem);
        }
        refreshPropertySheet();
    }

    private void refreshRenderers(Item activeLegendItem) {
        renderersComboBox.removeAllItems();

//        Item activeLegendItem = (Item) activeLegendsComboBox.getSelectedItem();
        if (activeLegendItem != null) {

            Collection<? extends LegendItemRenderer> renderers = Lookup.getDefault().lookupAll(LegendItemRenderer.class);
            for (LegendItemRenderer renderer : renderers) {

                if (renderer.isAnAvailableRenderer(activeLegendItem)) {
                    renderersComboBox.addItem(renderer);

                }
            }

        }
    }

    private void numberOfItemsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfItemsTextFieldActionPerformed
        PreviewController previewController = Lookup.getDefault().lookup(PreviewController.class);

        if (!numberOfItemsTextField.getText().isEmpty()) {

            int numberOfItems = Integer.parseInt(numberOfItemsTextField.getText());
            Item item = (Item) activeLegendsComboBox.getSelectedItem();
            if (LegendController.getInstance().updateItemDynamicPreviewProperties(item, numberOfItems)) {
                PreviewProperty[] dynamicProperties = item.getData(LegendItem.DYNAMIC_PROPERTIES);
                for (PreviewProperty property : dynamicProperties) {
                    previewController.getModel().getProperties().putValue(property.getName(), property.getValue());
                }
                refreshPropertySheet();
            }
        }
        
        previewController.refreshPreview();
    }//GEN-LAST:event_numberOfItemsTextFieldActionPerformed

    private void legendItemBuildersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legendItemBuildersComboBoxActionPerformed
        // clean combobox
        builderTypeComboBox.removeAllItems();
        ArrayList<String> tooltips = new ArrayList<String>();

        LegendItemBuilder builder = (LegendItemBuilder) legendItemBuildersComboBox.getSelectedItem();
        ArrayList<CustomLegendItemBuilder> availableBuilders = builder.getAvailableBuilders();
        for (CustomLegendItemBuilder availableBuilder : availableBuilders) {
            builderTypeComboBox.addItem(new CustomLegendItemBuilderWrapper(availableBuilder));
            tooltips.add(availableBuilder.getDescription());
        }

        tooltipRenderer.setTooltips(tooltips);
    }//GEN-LAST:event_legendItemBuildersComboBoxActionPerformed

    
    private void renderersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderersComboBoxActionPerformed
        Item item = (Item) activeLegendsComboBox.getSelectedItem();
        Object renderer = renderersComboBox.getSelectedItem();
        if (item != null && renderer != null) {
            item.setData(LegendItem.RENDERER, renderer);
        }
        previewUIController.refreshPreview();
    }//GEN-LAST:event_renderersComboBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeLegendLabel;
    private javax.swing.JComboBox activeLegendsComboBox;
    private javax.swing.JButton addLegendButton;
    private javax.swing.JComboBox builderTypeComboBox;
    private javax.swing.JComboBox legendItemBuildersComboBox;
    private javax.swing.JPanel legendManagerPanel;
    private javax.swing.JPanel legendPropertiesPanel;
    private javax.swing.JLabel numberOfItemsLabel;
    private javax.swing.JTextField numberOfItemsTextField;
    private javax.swing.JButton removeLegendButton;
    private javax.swing.JLabel rendererLabel;
    private javax.swing.JComboBox renderersComboBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(PreviewModel previewModel) {
    }

    @Override
    public JPanel getPanel() {
        refreshActiveLegendsComboBox();
        return this;
    }

    @Override
    public void unsetup() {
    }

    @Override
    public Icon getIcon() {
        return new ImageIcon();
    }

    @Override
    public String getPanelTitle() {
        return NbBundle.getMessage(LegendManagerUI.class, "LegendManagerUI.title");
    }

    private void registerLegendBuilders() {
        Collection<? extends LegendItemBuilder> availablebuilders = legendController.getAvailablebuilders();
        // cleaning combobox
        legendItemBuildersComboBox.removeAllItems();

        // registering builders
        for (LegendItemBuilder legendItemBuilder : availablebuilders) {
            legendItemBuildersComboBox.addItem(legendItemBuilder);
        }
    }

    class CustomLegendItemBuilderWrapper {

        public CustomLegendItemBuilder builder;

        public CustomLegendItemBuilderWrapper(CustomLegendItemBuilder builder) {
            this.builder = builder;
        }

        @Override
        public String toString() {
            return builder.getTitle();
        }
    }

    public class ComboboxToolTipRenderer extends DefaultListCellRenderer {

        private ArrayList<String> tooltips;

        @Override
        public Component getListCellRendererComponent(JList list, Object value,
                int index, boolean isSelected, boolean cellHasFocus) {

            JComponent comp = (JComponent) super.getListCellRendererComponent(list,
                    value, index, isSelected, cellHasFocus);

            if (-1 < index && null != value && null != tooltips) {
                list.setToolTipText(tooltips.get(index));
            }
            return comp;
        }

        public void setTooltips(ArrayList<String> tooltips) {
            this.tooltips = tooltips;
        }
    }
    private ComboboxToolTipRenderer tooltipRenderer;
}
